apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "FIAP.Diner.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "FIAP.Diner.labels" . | nindent 4 }}
data:
  ConnectionStrings__PostgreSql: Host={{ .Values.configmap.connectionstring.host }}:{{ .Values.configmap.connectionstring.port }};Database={{ .Values.configmap.connectionstring.database }};Username={{ .Values.configmap.connectionstring.user }};Password={{ .Values.configmap.connectionstring.password }}
